<?php

require_once dirname(__FILE__) . '/../../../lib/GestPayCrypt/GestPayCrypt.inc.php';

/**
 * Test class for GestPayCrypt.
 * Generated by PHPUnit on 2011-11-18 at 16:25:58.
 */
class GestPayCryptTest extends PHPUnit_Framework_TestCase
{
  /**
   * @var GestPayCrypt
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp()
  {
    $this->object = new GestPayCrypt;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown()
  {
  }

  /**
   * @covers {className}::{origMethodName}
   * @todo Implement testSetShopLogin().
   */
  public function testSetShopLogin()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers {className}::{origMethodName}
   * @todo Implement testSetCurrency().
   */
  public function testSetCurrency()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers {className}::{origMethodName}
   * @todo Implement testSetAmount().
   */
  public function testSetAmount()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers {className}::{origMethodName}
   * @todo Implement testSetShopTransactionID().
   */
  public function testSetShopTransactionID()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers {className}::{origMethodName}
   * @todo Implement testSetCardNumber().
   */
  public function testSetCardNumber()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers {className}::{origMethodName}
   * @todo Implement testSetDomainName().
   */
  public function testSetDomainName()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers {className}::{origMethodName}
   * @todo Implement testSetExpMonth().
   */
  public function testSetExpMonth()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers {className}::{origMethodName}
   * @todo Implement testSetExpYear().
   */
  public function testSetExpYear()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers {className}::{origMethodName}
   * @todo Implement testSetMIN().
   */
  public function testSetMIN()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers {className}::{origMethodName}
   * @todo Implement testSetCVV().
   */
  public function testSetCVV()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers {className}::{origMethodName}
   * @todo Implement testSetBuyerName().
   */
  public function testSetBuyerName()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers {className}::{origMethodName}
   * @todo Implement testSetBuyerEmail().
   */
  public function testSetBuyerEmail()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers {className}::{origMethodName}
   * @todo Implement testSetLanguage().
   */
  public function testSetLanguage()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers {className}::{origMethodName}
   * @todo Implement testSetCustomInfo().
   */
  public function testSetCustomInfo()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers {className}::{origMethodName}
   * @todo Implement testSetEncryptedString().
   */
  public function testSetEncryptedString()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers {className}::{origMethodName}
   * @todo Implement testGetShopLogin().
   */
  public function testGetShopLogin()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers {className}::{origMethodName}
   * @todo Implement testGetCurrency().
   */
  public function testGetCurrency()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers {className}::{origMethodName}
   * @todo Implement testGetAmount().
   */
  public function testGetAmount()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers {className}::{origMethodName}
   * @todo Implement testGetCountry().
   */
  public function testGetCountry()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers {className}::{origMethodName}
   * @todo Implement testGetVBV().
   */
  public function testGetVBV()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers {className}::{origMethodName}
   * @todo Implement testGetVBVrisp().
   */
  public function testGetVBVrisp()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers {className}::{origMethodName}
   * @todo Implement testGetShopTransactionID().
   */
  public function testGetShopTransactionID()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers {className}::{origMethodName}
   * @todo Implement testGetBuyerName().
   */
  public function testGetBuyerName()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers {className}::{origMethodName}
   * @todo Implement testGetBuyerEmail().
   */
  public function testGetBuyerEmail()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers {className}::{origMethodName}
   * @todo Implement testGetCustomInfo().
   */
  public function testGetCustomInfo()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers {className}::{origMethodName}
   * @todo Implement testGetAuthorizationCode().
   */
  public function testGetAuthorizationCode()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers {className}::{origMethodName}
   * @todo Implement testGetErrorCode().
   */
  public function testGetErrorCode()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers {className}::{origMethodName}
   * @todo Implement testGetErrorDescription().
   */
  public function testGetErrorDescription()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers {className}::{origMethodName}
   * @todo Implement testGetBankTransactionID().
   */
  public function testGetBankTransactionID()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers {className}::{origMethodName}
   * @todo Implement testGetTransactionResult().
   */
  public function testGetTransactionResult()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers {className}::{origMethodName}
   * @todo Implement testGetAlertCode().
   */
  public function testGetAlertCode()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers {className}::{origMethodName}
   * @todo Implement testGetAlertDescription().
   */
  public function testGetAlertDescription()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers {className}::{origMethodName}
   * @todo Implement testGetEncryptedString().
   */
  public function testGetEncryptedString()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers {className}::{origMethodName}
   * @todo Implement testEncrypt().
   */
  public function testEncrypt()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers {className}::{origMethodName}
   * @todo Implement testDecrypt().
   */
  public function testDecrypt()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers {className}::{origMethodName}
   * @todo Implement testToEncrypt().
   */
  public function testToEncrypt()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers {className}::{origMethodName}
   * @todo Implement testHttpGetResponse().
   */
  public function testHttpGetResponse()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers {className}::{origMethodName}
   * @todo Implement testHttpGetLine().
   */
  public function testHttpGetLine()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers {className}::{origMethodName}
   * @todo Implement testParsing().
   */
  public function testParsing()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

}
