<?php

require_once dirname(__FILE__) . '/../../../lib/GestPayCrypt/GestPayCrypt.inc.php';

/**
 * Test class for GestPayCryptHS.
 * Generated by PHPUnit on 2011-11-18 at 16:25:58.
 */
class GestPayCryptHSTest extends PHPUnit_Framework_TestCase
{
  /**
   * @var GestPayCryptHS
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp()
  {
    $this->object = new GestPayCryptHS;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown()
  {
  }

  /**
   * @covers {className}::{origMethodName}
   * @todo Implement testHttpGetLine().
   */
  public function testHttpGetLine()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

}
